# Generated by Django 5.2.6 on 2025-09-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(default='Present', max_length=50),
        ),
    ]
